### ISSUE TITLE
下載失敗

### ISSUE THREAD

**Issue by ardidi** [Yukaii/readmoo-api#6]
一直下載失敗啊QQ

下載 "交易聖經（二版）" 失敗！
書籍已下載至：

**Comment by Yukaii** [comment]
😂 我晚點來看看哪裡失效了

**Comment by ardidi** [comment]
想把epub轉去kobo上面看XD

**Comment by Yukaii** [comment]
@ardidi 我推了一版來幫助除錯，你可以用以下指令安裝此版本

```bash
npm i Yukaii/readmoo-api#80460f8 -g
```

再麻煩你把錯誤的訊息貼上來

**Comment by ardidi** [comment]
{ Error: getaddrinfo ENOTFOUND reader.readmoo.com reader.readmoo.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'reader.readmoo.com',
  host: 'reader.readmoo.com',
  port: 443,
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        Cookie:
         'readmoo=ik57kdlhcgjtff8nhop6dnc3641vmnj7; CloudFront-Key-Pair-Id=APKAJLIHITVNV2K77LNA; CloudFront-Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9yZWFkZXIucmVhZG1vby5jb20vZWJvb2svMzMxLzExMDMzMS8xMDQ1MjIvMV8wL2Z1bGwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU2Mjc5NzU1Mn19fV19; CloudFront-Signature=iYwaYrjUUIsaEmdE5zkUR5FKK6B1RcK%7EJoNKj7IKEb29d-X7U1rvBVtHOoxf9DT41r7%7EbpW1RjH0wZ5uAYYt9CdWkzx94zbWmL60yMuLIbF0gZQOzVD3sb-b6oNN7GEbk8a5VfeN1F8QiXMj7Jc4SFLu%7EH3YfDKYA1zC1pfd9oCUS6jGkSPFc3NVxNyGcxjgT6UpDlyoilGfI85Yg-sy--LFAGtu4y774XBnuRObx6hG%7EJYTPzBeb90C--cAiUp-xzDDppnrZE77pKeCzcuP%7EGLwfGSnzUXr0ZORJK3AS-mDybzQG%7EXhWy%7E2ZJADOGoMHZ-TAmkdfgnz8kxqheJZ7A__;',
        'User-Agent': 'axios/0.18.1' },
     method: 'get',
     responseType: 'stream',
     url:
      'https://reader.readmoo.com/ebook/331/110331/104522/1_0/full/OEBPS/Images/p083-2.jpg',
     data: undefined },
  request:
   Writable {
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        emitClose: true,
        autoDestroy: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     _events:
      [Object: null prototype] {
        response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options:
      { protocol: 'https:',
        maxRedirects: 21,
        maxBodyLength: 10485760,
        path: '/ebook/331/110331/104522/1_0/full/OEBPS/Images/p083-2.jpg',
        method: 'get',
        headers: [Object],
        agent: undefined,
        auth: undefined,
        hostname: 'reader.readmoo.com',
        port: null,
        nativeProtocols: [Object],
        pathname: '/ebook/331/110331/104522/1_0/full/OEBPS/Images/p083-2.jpg' },
     _redirectCount: 0,
     _redirects: [],
     _requestBodyLength: 0,
     _requestBodyBuffers: [],
     _onNativeResponse: [Function],
     _currentRequest:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         'GET /ebook/331/110331/104522/1_0/full/OEBPS/Images/p083-2.jpg HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nCookie: readmoo=ik57kdlhcgjtff8nhop6dnc3641vmnj7; CloudFront-Key-Pair-Id=APKAJLIHITVNV2K77LNA; CloudFront-Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9yZWFkZXIucmVhZG1vby5jb20vZWJvb2svMzMxLzExMDMzMS8xMDQ1MjIvMV8wL2Z1bGwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU2Mjc5NzU1Mn19fV19; CloudFront-Signature=iYwaYrjUUIsaEmdE5zkUR5FKK6B1RcK%7EJoNKj7IKEb29d-X7U1rvBVtHOoxf9DT41r7%7EbpW1RjH0wZ5uAYYt9CdWkzx94zbWmL60yMuLIbF0gZQOzVD3sb-b6oNN7GEbk8a5VfeN1F8QiXMj7Jc4SFLu%7EH3YfDKYA1zC1pfd9oCUS6jGkSPFc3NVxNyGcxjgT6UpDlyoilGfI85Yg-sy--LFAGtu4y774XBnuRObx6hG%7EJYTPzBeb90C--cAiUp-xzDDppnrZE77pKeCzcuP%7EGLwfGSnzUXr0ZORJK3AS-mDybzQG%7EXhWy%7E2ZJADOGoMHZ-TAmkdfgnz8kxqheJZ7A__;\r\nUser-Agent: axios/0.18.1\r\nHost: reader.readmoo.com\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/ebook/331/110331/104522/1_0/full/OEBPS/Images/p083-2.jpg',
        _ended: false,
        res: null,
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl:
      'https://reader.readmoo.com/ebook/331/110331/104522/1_0/full/OEBPS/Images/p083-2.jpg' },
  response: undefined }

**Comment by Yukaii** [comment]
@ardidi 拍寫不小心讓你把 credential 貼上來，看起來是圖片下載失敗的問題，我試著處裡這個錯誤

**Comment by Digworm** [comment]
您好，我剛剛嘗試，也是一直出現下載失敗

**Comment by Digworm** [comment]
![01](https://user-images.githubusercontent.com/3294420/67473939-264ad600-f686-11e9-93ab-89475a42667a.jpg)
[2019-10-24T09_41_21_374Z-debug.log](https://github.com/Yukaii/readmoo-api/files/3766821/2019-10-24T09_41_21_374Z-debug.log)

**Comment by chusiang** [comment]
附上敝人的執行失敗訊息，希望幫得上忙。

1. 安裝 debug 版的 Yukaii/readmoo-api。

    ```
    [ user@mac ~ ] - 17:53
    $ npm i Yukaii/readmoo-api#80460f8 -g
    /usr/local/bin/readmoo-dl -> /usr/local/lib/node_modules/readmoo-api/out/cli.js
    + readmoo-api@1.0.0
    updated 1 package in 6.752s
    ```

1. credentials.json 取得的東西似乎變少了。

    ```
    [ user@mac ~ ] - 17:54
    $ cat ~/.readmoo-api/credentials.json
    {
      "readmoo": "readmoo=********************************;"
    }
    ```

1. readmoo-dl 執行失敗的錯誤訊息。

    ```
    [ user@mac ~ ] - 17:55
    $ readmoo-dl
    ...

    { Error: getaddrinfo ENOTFOUND reader.readmoo.comundefinedmeta-inf reader.readmoo.comundefinedmeta-inf:443
        at errnoException (dns.js:50:10)
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
      code: 'ENOTFOUND',
      errno: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'reader.readmoo.comundefinedmeta-inf',
      host: 'reader.readmoo.comundefinedmeta-inf',
      port: 443,
      config:
       { adapter: [Function: httpAdapter],
         transformRequest: { '0': [Function: transformRequest] },
         transformResponse: { '0': [Function: transformResponse] },
         timeout: 0,
         xsrfCookieName: 'XSRF-TOKEN',
         xsrfHeaderName: 'X-XSRF-TOKEN',
         maxContentLength: -1,
         validateStatus: [Function: validateStatus],
         headers:
          { Accept: 'application/json, text/plain, */*',
            Cookie: 'readmoo=********************************;',
            'User-Agent': 'axios/0.18.1' },
         method: 'get',
         url: 'https://reader.readmoo.comundefinedMETA-INF/container.xml',
         data: undefined },
      request:
       Writable {
         _writableState:
          WritableState {
            objectMode: false,
            highWaterMark: 16384,
            finalCalled: false,
            needDrain: false,
            ending: false,
            ended: false,
            finished: false,
            destroyed: false,
            decodeStrings: true,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: true,
            bufferProcessing: false,
            onwrite: [Function: bound onwrite],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: false,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: [Object] },
         writable: true,
         domain: null,
         _events:
          { response: [Function: handleResponse],
            error: [Function: handleRequestError] },
         _eventsCount: 2,
         _maxListeners: undefined,
         _options:
          { protocol: 'https:',
            maxRedirects: 21,
            maxBodyLength: 10485760,
            path: '/container.xml',
            method: 'get',
            headers: [Object],
            agent: undefined,
            auth: undefined,
            hostname: 'reader.readmoo.comundefinedmeta-inf',
            port: null,
            nativeProtocols: [Object],
            pathname: '/container.xml' },
         _redirectCount: 0,
         _redirects: [],
         _requestBodyLength: 0,
         _requestBodyBuffers: [],
         _onNativeResponse: [Function],
         _currentRequest:
          ClientRequest {
            domain: null,
            _events: [Object],
            _eventsCount: 6,
            _maxListeners: undefined,
            output: [],
            outputEncodings: [],
            outputCallbacks: [],
            outputSize: 0,
            writable: true,
            _last: true,
            upgrading: false,
            chunkedEncoding: false,
            shouldKeepAlive: false,
            useChunkedEncodingByDefault: false,
            sendDate: false,
            _removedConnection: false,
            _removedContLen: false,
            _removedTE: false,
            _contentLength: 0,
            _hasBody: true,
            _trailer: '',
            finished: true,
            _headerSent: true,
            socket: [Object],
            connection: [Object],
            _header: 'GET /container.xml HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nCookie: readmoo=********************************;\r\nUser-Agent: axios/0.18.1\r\nHost: reader.readmoo.comundefinedmeta-inf\r\nConnection: close\r\n\r\n',
            _onPendingData: [Function: noopPendingOutput],
            agent: [Object],
            socketPath: undefined,
            timeout: undefined,
            method: 'GET',
            path: '/container.xml',
            _ended: false,
            res: null,
            aborted: undefined,
            timeoutCb: null,
            upgradeOrConnect: false,
            parser: null,
            maxHeadersCount: null,
            _redirectable: [Circular],
            [Symbol(outHeadersKey)]: [Object] },
         _currentUrl: 'https://reader.readmoo.comundefinedmeta-inf/container.xml' },
      response: undefined }
    ...

**Comment by Yukaii** [comment]
看到相關專案 readmoo-dl 做了點修正，主要是改 Referer，有沒有善心大德要來 PR 一下啊 🤣 

應該是一行修正就可以了。因為我最近沒在 readmoo 買書，修這個我自己也用不到啊 XD

可以參考 ruby 版的修正：https://github.com/msglight4874/readmoo-dl/commit/d4333d3c4580dfb514df2091f169dd0538d33e82

等不及的話直接去用 ruby 版的也可以，上 GitHub 找了下也有其它相關的專案可以用 https://github.com/search?q=readmoo

**Comment by Digworm** [comment]
有試了，還是不行，不過還是感謝您

**Comment by Yukaii** [comment]
那個，v1.1.0 版釋出了，大家可以用以下指令安裝

```bash
npm i Yukaii/readmoo-api#v1.1.0 -g
```

再看看有沒有什麼問題，讓我們感謝 @msglight4874 的貢獻 🍻
